### ISSUE TITLE
点击生成的链接总是反馈Invalid Session Key, please try again

### ISSUE THREAD

**Issue by yixiaxian** [jonirrings/xor#11]
Message

Invalid Session Key, please try again

无论登陆进去切的有多块，都是这个，光猫型号也是TEWA-708E，硬件版本V1.0，软件版本Tianyi_V1.0.2，求问大神怎么解决这个问题，有没有什么操作要点？

**Comment by yixiaxian** [comment]
http://192.168.1.1:8080/usbbackup.cmd?action=backupeble&set2_sessionKey=set2_sessionKey_XXX
在之前的issue里面找到了这个答案，解决了问题，谢谢！

**Comment by jonirrings** [comment]
找到就好，机器版本不同，这个session key的名字也不同
