### ISSUE TITLE
页面被换成动态页面了，请问怎么操作？

### ISSUE THREAD

**Issue by leafsnow** [jonirrings/xor#12]
![1](https://user-images.githubusercontent.com/6291246/91626733-6edcc980-e9e4-11ea-9055-fe222496ab28.png)

**Comment by jonirrings** [comment]
额，我这边机器不是这个样，暂时帮不了你。只能给你提供个思路。
1. 找到关键页面，然后用postman请求看看返回的数据，慢慢判断拿到配置的方法。
2. 找到关键函数，直接在console内执行，看看能不能导出配置。

**Comment by leafsnow** [comment]
感谢楼主的思路，不过我不是前端方向的，就不折腾了，等待有缘人 :)
