### ISSUE TITLE
拿到超密登录进去后尝试添加静态路由，然后静态路由页面无法访问

### ISSUE THREAD

**Issue by john2088** [jonirrings/xor#13]
尝试在路由器的：网络>路由配置，这个页面添加静态路由，添了一条后就不能再访问这一页
这个页面直接变成192.168.1.1 didn’t send any data.

**Comment by jonirrings** [comment]
十有八九是配置崩了，估计这猫的路由功能可能是残废，或者配置保存得有问题导致了读不出来。
还原之前导出的配置文件吧。

**Comment by john2088** [comment]
我试试，谢谢撸主
