### ISSUE TITLE
因无法上网，电信师傅上门弄好后，最新的配置文件已经找不到超管密码了。

### ISSUE THREAD

**Issue by codering** [jonirrings/xor#14]
按教程获得了密码，用路由器拨号，我还设置了同一个网口来接收itv。
用了2周突然无法上网，就让电信师傅上门，弄好以后，最新的备份文件搜索不到“TeleComAccount”。

[aa.txt](https://github.com/jonirrings/xor/files/5611806/aa.txt)

**Comment by jonirrings** [comment]
这种情况暂出没解了。估计固件被升级版本了，如果和以前是相同版本的话，还可以还原以前的配置文件，死马当活马医一把……
