### ISSUE TITLE
telnet 在新版固件上似乎无法启用

### ISSUE THREAD

**Issue by jia-kai** [jonirrings/xor#15]
不知道老版本固件什么情况…… 我的版本是 `Tianyi_V1.0.3`。

现在的配置文件里面有：
```xml
      <X_CT-COM_ServiceManage>      
        <FtpPassword>PCvSF</FtpPassword>
        <TelnetUserName>telnetadmin</TelnetUserName>
        <TelnetPassword>telnetadmin</TelnetPassword>
        <Tr69SetFtpLan>TRUE</Tr69SetFtpLan>
        <Tr69SetTelnetLan>TRUE</Tr69SetTelnetLan>
      </X_CT-COM_ServiceManage>
```

ftp 用 ftpadmin:PCvSF 昨天连接成功过一次，但后来就返回 421 incorrect login。telnet 看了下 ftp 貌似可以直接用来更新固件

```txt
% telnet 192.168.1.1 21
Trying 192.168.1.1...
Connected to 192.168.1.1.
Escape character is '^]'.
220 Ftp firmware update utility
```

而 telnet 是直接连接超时。访问 http://192.168.1.1:8080/enableTelnet.html 会直接被 redirect:

```txt
HTTP/1.1 200 Ok
Server: ty_httpd
Cache-Control: no-cache
Date: Tue, 09 Feb 2021 15:50:19 GMT
Content-Type: text/html
Connection: close

<HTML><HEAD><script language='javascript'>
parent.location='login.html'
</script></HEAD><BODY></BODY></HTML>
```

想请教下，http://192.168.1.1:8080/enableTelnet.html 这个地址原来是从哪儿找到的？我试试新版上能不能找到类似的入口

**Comment by jonirrings** [comment]
如果固件配置里面有telnet的话，可以改配置文件再导入，使能telnet。
拿工具扫描一下端口，手机用fing最简单，电脑nmap。
实在不行就没辙了。这个地址是网上找的，不过telnet进去后，在`/webs`里面也能找到大批`.html`文件，url和文件路径瞎猜是直接映射。

**Comment by 1564307973** [comment]
我发现了这个，不知道有不有用

https://b23.tv/dFxvhx

**Comment by jonirrings** [comment]
@1564307973 好像没用……。先关了
