### ISSUE TITLE
没有backupeble这一项，也没有USB恢复

### ISSUE THREAD

**Issue by lzlyt** [jonirrings/xor#16]
大佬们好，我的是TEWA1000E，没有backupeble这一项，也没有USB恢复这一项，但是是有USB接口的，不加8080登录后台可以看到U盘，何解啊?

**Comment by lzlyt** [comment]
已经解决，没有backupeble和USB恢复，直接搜索set3_sessionKey
地址是http://192.168.0.1:8080/usbbackup.cmd?action=backupeble&set3_sessionKey=set3_sessionKey_XXX
广西电信

**Comment by jonirrings** [comment]
@lzlyt 666，解决了就好。大兄弟你起床真早啊，😄
