### ISSUE TITLE
插入了USB但没有USB快速恢复选项

### ISSUE THREAD

**Issue by cui0v0** [jonirrings/xor#17]
设备型号 TEWA-1000E
硬件版本 V1.0 
软件版本 Tianyi_V1.0.2

如图
![image](https://user-images.githubusercontent.com/29875719/131055261-d6f8bc48-3164-487f-8e7a-e6ff87c40b67.png)
![image](https://user-images.githubusercontent.com/29875719/131055353-17b486fe-97ec-4448-bc73-6b4e1b588f67.png)
插入到USB能够正常被识别
![image](https://user-images.githubusercontent.com/29875719/131055283-92c26f42-7f6e-44a8-aa0d-947f7f560991.png)

地区是湖北武汉

**Comment by cui0v0** [comment]
尝试过#16的方法，把set1~8_sessionKey都试过了，3、4搜得到但不是USB快速恢复

**Comment by jonirrings** [comment]
……连backup关键字也找不到的话，我这个套路就应该没效果了

**Comment by linwanxiaoyehua** [comment]
https://koolshare.cn/thread-203088-1-1.html 看这个

**Comment by jonirrings** [comment]
@linwanxiaoyehua 666，老哥探索精神厉害。
另外有个思路，就是把导出的xml里面添加上超密，然后再转换一次，导回去，没试过，怕搞跪了，哈哈哈。

**Comment by cui0v0** [comment]
目前光猫已经换成华为的HN8145V了，代码完全不一样了，所以https://koolshare.cn/thread-203088-1-1.html 的方法可行性我试不了
