### ISSUE TITLE
操作到console那步出错

### ISSUE THREAD

**Issue by bbmimi** [jonirrings/xor#2]
输入代码后反馈: 
VM244:1 Uncaught ReferenceError: sessionKey is not defined
    at <anonymous>:1:64
求解!!

**Comment by jonirrings** [comment]
第5步要求前面几步一定要正确执行来着。
那你试试底部`其他型号`的那种方式？寻找关键字，手动拼凑url的那种方式。

**Comment by mmfan** [comment]
708g没session,怎么办，给你发邮件了能架联系方式吗？多谢

**Comment by jonirrings** [comment]
@mmfan 已经邮件回复你了

**Comment by bbmimi** [comment]
![TIM截图20200308222406](https://user-images.githubusercontent.com/47265748/76205331-f6ffc480-6234-11ea-9b21-7a0c6a8a9f50.png)
感谢,不过还是不行!应该是运营商后台改了,里面没有var sessionKey 这一行!

**Comment by jonirrings** [comment]
@bbmimi 不见得需要sessionKey这个关键字，你找到backupeble这个url的拼接参数，自行拼接就行。

**Comment by jonirrings** [comment]
@bbmimi 搞定了么？我先关闭issue了哦，没搞定你再点reopen就是。

**Comment by SeanChengN** [comment]
@mmfan 我也是708g，你解决了吗？

**Comment by jonirrings** [comment]
@SeanChengN 在设备管理页面的调试模式下搜索backupeble，将附近的截图发出来看看嘛。
我没有设备不知道具体情况。

**Comment by SeanChengN** [comment]
@jonirrings 似乎没有变量sessionKey
![微信截图_20200313193902](https://user-images.githubusercontent.com/20624068/76617958-5c6bf200-6562-11ea-88c5-821211fc398a.png)

**Comment by jonirrings** [comment]
@SeanChengN 截图的倒数第三行，那个set_sessionKey_887就是关键，是每次都会变动的。
因此：你的url就是
`/usbbackup.cmd?action=backupeble&set_sessionKey=set_sessionKey_XXX`
把`XXX`换成这里自动变化的数字。我在tewa-1000e看到的也是这种。

要是成功了有劳即使回复，我关闭issue。

@mmfan 你也参考试试。

**Comment by SeanChengN** [comment]
@jonirrings 厉害了，还真是这样，十分感谢

**Comment by bbmimi** [comment]
@jonirrings 终于搞定,感谢大神!!!

**Comment by bowltwood** [comment]
@jonirrings 从https://koolshare.cn/thread-166510-2-1.html这里过来的，特意来谢谢大神。。已获取超密

**Comment by codering** [comment]
> @SeanChengN 截图的倒数第三行，那个set2_sessionKey_887就是关键，是每次都会变动的。
> 因此：你的url就是
> `http://192.168.1.1:8080/usbbackup.cmd?action=backupeble&set2_sessionKey=set2_sessionKey_XXX`
> 把`XXX`换成这里自动变化的数字。我在tewa-1000e看到的也是这种。
> 
> 要是成功了有劳及时回复，我关闭issue。
> 
> @mmfan 你也参考试试。

Good!

**Comment by Adrien0805** [comment]
我在“管理”项目里找不到set2_sessionKey，但在“应用”里找到了，而且这几年都没变过密码，供大家参考（型号TEWA-1000G，V1.1）
<img width="755" alt="1" src="https://github.com/jonirrings/xor/assets/33699328/0536d448-948b-4173-8a1c-3915669e903a">

<img width="869" alt="2" src="https://github.com/jonirrings/xor/assets/33699328/f095a527-0ccf-4c69-afc9-f91b88f8e02f">

**Comment by jonirrings** [comment]
最近有个通过小翼管家抓包获取超密的方式，可以参考一下。
@Adrien0805

**Comment by jonirrings** [comment]
最近有个通过小翼管家抓包获取超密的方式，可以参考一下。
@Adrien0805
