### ISSUE TITLE
如设备管理页面下无set2_sessionKey_xxx解决办法

### ISSUE THREAD

**Issue by Linnnnnncoln** [jonirrings/xor#20]
广西电信 TEWA_1000E 近似型号可参考
硬件版本V1.0
软件版本Tianyi_V1.0.2
1.在192.168.1.1:8080使用useradmin登陆后转到管理-设备管理页面
2.打开审查元素-Sources下点击mainFrame-找到set3_sessionKey_XXX后复制（该xxx会随着每次登陆而变动）
![微信图片_20220216145250](https://user-images.githubusercontent.com/61079175/154211662-d5be95f1-d064-4717-9632-918f39a735f9.png)
3.随后在浏览器键入
`http://192.168.1.1:8080/usbbackup.cmd?action=backupeble&set3_sessionKey=XXXXXXXXXXX`
（XXX替换为复制下来的set3_sessionKey_xxx）即可来到备份页面，但备份选项为灰色，
转到Console，键入
```usbsubarea = {
selectedIndex:0,
value:"never_mind...",
 options:[
      {value:"usb1_1"}
             ]
};
btnApply();
```
键入后，备份文件将会自动保存进入U盘内，可登录`192.168.1.1`在存储管理-存储设置下找到e8_Config_Backup文件夹。
4.将U盘插回电脑，使用xor解密后即可找到超级密码。

**Comment by jonirrings** [comment]
点赞，晚点我在readme里面把这个issue加个链接

**Comment by Linnnnnncoln** [comment]
2022/6/25 
疑似失效，软件版本无变动。查看sources发现，疑似电信远程施法封堵了。
目前情况如下，set3_sessionKey_xxx会自动刷新，导致打开的页面永远为
Message

Invalid Session Key, please try again，
还能获取的获取后千万不要断电，白天咨询了一下装维，1000E/G重启后会自动重新下发配置，并更改超级管理密码。

**Comment by Linnnnnncoln** [comment]
> 2022/6/25 疑似失效，软件版本无变动。查看sources发现，疑似电信远程施法封堵了。 目前情况如下，set3_sessionKey_xxx会自动刷新，导致打开的页面永远为 Message
> 
> Invalid Session Key, please try again， 还能获取的获取后千万不要断电，白天咨询了一下装维，1000E/G重启后会自动重新下发配置，并更改超级管理密码。

(疑似GitHub有电信内鬼

**Comment by jonirrings** [comment]
电信的系统都是乙方承建的……

**Comment by Linnnnnncoln** [comment]
> 

哈哈，那就是天邑
