### ISSUE TITLE
加密后的xml文件怎么加密回cfg文件

### ISSUE THREAD

**Issue by iuuzeo** [jonirrings/xor#25]
加密后的xml文件怎么加密回cfg文件，默认的超密被改了（光猫未注册情况），我是需要修改回默认的超密

**Comment by jonirrings** [comment]
这个tewa系列的做法是xor，根据xor的特性，A XOR 0xFF = B, B XOR 0xFF=A。
换言之, `xor.exe 密文文件`得到`明文文件`，`xor.exe 明文文件`得到`密文文件`。
