### ISSUE TITLE
TEWA-800E访问8080端口提示404 

### ISSUE THREAD

**Issue by wuwentao** [jonirrings/xor#3]
1. 普通80端口可以获取管理员权限，可以开通ftp权限，可以登录，但还想开通telnet
2. 目前可以确认8080端口是开放的，登录页面是有特殊地址？
直接打开提示：http://192.168.1.1:8080/

```
HTTP ERROR 404
Problem accessing /. Reason:

    NOT_FOUND
Powered by Jetty://
```

**Comment by jonirrings** [comment]
我没弄过这个型号唉，天邑光猫配置工具能弄么？或者直接在80上enable telnet 页面可以么？
