### ISSUE TITLE
你好，求助

### ISSUE THREAD

**Issue by git365888** [jonirrings/xor#4]
按照你的教程下载了路由器CFG文件，但是不懂怎么解密。使用router data view或者附件的xor解密，router data view找不到，附件的xor不知如何使用，百度也搜不到。求个解密cfg文件的详细教程

**Comment by jonirrings** [comment]
@git365888
假设你是win系统 
打开cmd，把附件的 xor.exe拖进cmd里面，点一下空格，再把加密的cfg文件拖进cmd里面，点一下回车。
然后在你cfg所在目录下就会生成一个同名的xml文件，那个就是解密的。

**Comment by git365888** [comment]
不好意思再打扰一下，附件没看到xor.exe文件呢，压缩包里面只有main.rs、.gitignore、Cargo.toml

**Comment by jonirrings** [comment]
@git365888 ……看来你是GitHub萌新啊……在code页面点击release，里面就是。

**Comment by git365888** [comment]
刚注册的账号，搞好了 非常感谢

**Comment by jonirrings** [comment]
@git365888  搞定了就好～～

**Comment by ming666668888** [comment]
打开就闪退  是电脑缺少什么环境吗？

**Comment by jonirrings** [comment]
@ming666668888 用cmd命令跑，没有图形界面。也可以用那个[链接](https://jonirrings.github.io/xor/)进去，用网页跑。

**Comment by ming666668888** [comment]
> @ming666668888用cmd命令跑，没有图形界面。也可以用那个[链接](https://jonirrings.github.io/xor/)进入，用网页跑。

我用了cmd  但下一步输入什么代码或指令  求帮忙
D:\360Downloads\ztecfg_v0.1.0_win\ztecfg>ztecfg ctce8_F673AV9a.cfg
usage: ztecfg [-h] [-u cfg_file | -p cfg_file xml_file] [-o file] [-f] [-v]
ztecfg: error: unrecognized arguments: ctce8_F673AV9a.cfg

**Comment by SimingLiu** [comment]
实测 EPON天翼网关  TEWA-750E 可以使用。多谢
