### ISSUE TITLE
只有一个光猫和电视机顶盒，如何实现网络和iptv走同一个wifi同时使用？

### ISSUE THREAD

**Issue by sxdxyxy** [jonirrings/xor#5]

**Comment by jonirrings** [comment]
如果光猫上可以认证IPTV，那么可以使用路由表+ IGMP Snooping + IGMP proxy来实现IPTV和网络共存在一个网下，但IPTV各地差异太大了，细节部分只能自己摸索。
我这儿只能在IPTV机顶盒上认证，我是用OpenWRT路由器冒充机顶盒认证，再在路由器上实施上述策略，完成的网络和IPTV同在一个网络内。
相关内容还是得去KoolShare爬帖子，譬如[这个](http://koolshare.cn/thread-120569-1-1.html)
因为与项目无关，我关issue了哈。
