### ISSUE TITLE
请教开启telnet的用途

### ISSUE THREAD

**Issue by BetaXOi** [jonirrings/xor#6]
除非能够提权到root，否则感觉也没啥用啊。

请假各位开启telnet的实际用途

**Comment by jonirrings** [comment]
就图一个乐，有时候telnet到猫上面去top一下看看资源使用率之类的。这不是论坛，估计也没其他人回复，哈哈哈。

**Comment by BetaXOi** [comment]
谢谢，主要就是想问问看，万一有人知道root密码或提权漏洞呢。

**Comment by BetaXOi** [comment]
另外，分享一个闭源的软件，可以查看大量光猫或路由的加密配置文件

**Comment by jonirrings** [comment]
我在readme里面提到就是这个软件来着。
telnet进去可以找到passwd文件，然后每次升级后，可以看看这个文件有木有变化，如果没变也许就可以拿机器暴力算root的密码hash试试。

**Comment by cers000** [comment]
暴力计算太难了，几乎不太可能
我的密码文件打开如下
root:$1$2s7kCsHV$rPN0P1crHzM7TX0w0W2Js0:0:0:Administrator:/:/bin/sh
谁要是能算出来麻烦请告诉我，光猫是TEWA-708E，密码加密好像是加盐的md5
