### ISSUE TITLE
感谢！

### ISSUE THREAD

**Issue by chenkehao1998** [jonirrings/xor#7]
感谢！用了你的方法成功get到了密码，目前我试了多个方法唯一可以用的
虽然有些小细节上不一样 虽然同一个机型但是那个sessionkey不能按照你的链接 
但是大概意思就是要进入到备份的页面  然后读了下js代码 自己拼串进去了
但是你的xor文件还是不会使用，不知道是不是兼容性的问题，打开直接闪退

**Comment by jonirrings** [comment]
@chenkehao1998 那个不是图形工具来着 可以参考 #4 
拿到密码就行
