### ISSUE TITLE
TEWA-1000E 明文后，找不到 TeleCom 字样

### ISSUE THREAD

**Issue by seabornlee** [jonirrings/xor#8]
升级千兆，师傅下午来，纯兴趣研究。
根据您的回答，备份出了文件，用 xor 转换出了 xml 文件，找到几个像密码的字段，都登录不成功。
[p.txt](https://github.com/jonirrings/xor/files/4465932/p.txt)

**Comment by jonirrings** [comment]
卧槽你的系统版本号是多少哦？还是说没过电信的光猫注册认证，还没有超密？师傅调整过后再试试～～
